name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
             node-version: '16.14.2'
      # Install dependencies
      - run: npm install
      # Transform Figma Tokens JSON to something Style Dictionary can read
      - run: npx token-transformer tokens.json tokens/global.json global
      # Create a light theme, exclude the global tokens
      - run: npx token-transformer tokens.json tokens/light.json global,light,theme global
      # Create a dark theme, exclude the global tokens
      - run: npx token-transformer tokens.json tokens/dark.json global,dark,theme global
      # Convert tokens according to Style Dictionary config
      - run: node build.js
      # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
